package nostra.resourceed.gui;

import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 * A class generated by eclipse to access the strings in the file
 * messages.properties.
 */
public class Messages
{
    private static final String BUNDLE_NAME = "messages"; //$NON-NLS-1$

    private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle.getBundle(BUNDLE_NAME);

    private Messages()
    {
    }

    public static String get(String key)
    {
        try
        {
            return RESOURCE_BUNDLE.getString(key);
        }
        catch (MissingResourceException e)
        {
            return '$' + key + '$';
        }
    }
}
